import { TwoWayDataBindingComponent } from "./two-way-data-binding/two-way-data-binding.component";
import { Component } from "@angular/core";
import { HelloComponent } from "./hello/hello.component";
import { DataBindingComponent } from "./data-binding/data-binding.component";

// function log(target, name, descriptor) {
//   console.log(target, name, descriptor);
//   //stor the original function in a var
//   const original = descriptor.value;
//   // do some manipulation with description.value
//   //original returns "hey there twice"
//   //original()
//   descriptor.value = function(...args) {
//     console.log("Arguments ", args, " were passed in this function");
//     const result = original(args);
//     console.log("The result of this function is  ", result);
//     return result;
//   };
//   //return the descriptor
//   return descriptor;
// }

// function classLog(className) {
//   console.log(className);
//   return (...args) => {
//     console.log("Arguments ", args, " were passed in this function");
//     return new className(...args);
//   };
// }

// @classLog
// class myExampleClass {
//   constructor(arg1, arg2) {
//     console.log("constructor fired!");
//   }
// }

//const myClass = new myExampleClass(5, 10);

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent {
  title = "intro-angular";

  constructor() {
    console.log(
      "This statement was generated by the constructor!",
      this.aSimpleMethod(5, 2)
    );
  }
  //@log is a decorator.
  //it decorates a method and executes when the method is called
  //@log
  aSimpleMethod(a, b) {
    return a * b;
  }
}
